# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses (https://spdx.org/licenses/)
allow_licenses:
  - Apache-2.0
  - MIT
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Python-2.0
  - Python-2.0.1
  - LGPL-3.0
  - CAL-1.0
  - Unlicense
  - MPL-2.0
  - 0BSD
  - CC-BY-4.0
  - BlueOak-1.0.0
