# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses (https://spdx.org/licenses/)
allow-licenses:
  - Apache-2.0
  - MIT
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - (Apache-2.0 OR MIT) AND BSD-3-Clause
  - (MIT OR Apache-2.0) AND Unicode-DFS-2016
  - MIT/Apache-2.0
