# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses (https://spdx.org/licenses/)
allow-licenses:
  - Apache-2.0
  - MIT
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - (Apache-2.0 OR MIT) AND BSD-3-Clause
  - (MIT OR Apache-2.0) AND Unicode-DFS-2016
  - BSD-2-Clause AND BSD-3-Clause
  - Python-2.0
  - Python-2.0.1
  - LGPL-3.0
  - LGPL-2.0-only AND LGPL-2.1-or-later # astroid
  - CAL-1.0
  - Apache-2.0 AND LGPL-3.0-or-later AND MIT
  - Apache-2.0 AND LGPL-3.0-or-later
  - Unlicense
  - GPL-2.0-only AND GPL-3.0-or-later AND LGPL-2.1-only AND MPL-1.1	 # pyphen
  - GPL-3.0 AND GPL-3.0-only AND GPL-3.0-or-later AND LGPL-3.0-only	 # pyxlsb
  - CAL-1.0 AND HPND  # Pillow
  - MPL-2.0
  - 0BSD
  - BSD-2-Clause AND MIT
